name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.7', '3.8', '3.9', '3.10.0' ]
        exclude:
          - os: windows-latest
            python-version: 3.7

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Mamba install dependencies
      run: mamba install python=${{ matrix.python-version }} pip

    - name: Install akernel
      run: |
        pip install .[test]

    - name: Check style and types
      run: |
        black --check akernel
        ruff check akernel
        mypy akernel

    - name: Run tests
      run: |
        akernel --help
        test -f ${CONDA_PREFIX}/share/jupyter/kernels/akernel/kernel.json
        pytest akernel/tests -v
