name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.8', '3.9', '3.10.0', '3.11' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup conda
      uses: mamba-org/setup-micromamba@v1
      with:
        init-shell: bash powershell
        cache-environment: true
        post-cleanup: 'all'
        environment-name: test-env
        create-args: >-
          python=${{ matrix.python-version }}
          pip

    - name: Install akernel
      run: |
        micromamba activate test-env
        pip install .[test]

    - name: Check style and types
      run: |
        micromamba activate test-env
        black --check akernel
        ruff check akernel
        mypy akernel

    - name: Run tests
      run: |
        micromamba activate test-env
        akernel --help
        test -f ${CONDA_PREFIX}/share/jupyter/kernels/akernel/kernel.json
        pytest akernel/tests -v
