name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install akernel
      run: |
        pip install . --group test

    - name: Check style and types
      run: |
        ruff check --show-fixes
        ruff format --check
        mypy src

    - name: Run tests
      run: |
        akernel --help
        test -f ${pythonLocation}/../share/jupyter/kernels/akernel/kernel.json
        pytest -v --reruns 5
